name: Scheduled MongoDB Backup

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MongoDB tools
        run: |
          sudo apt update
          sudo apt install -y mongodb-clients awscli

      - name: Run backup script
        run: |
          ./backup.sh
